name: haskell-leetcode
version: 0.1.0.0

executables:
  p1:
    main: Main.hs
    source-dirs: problems/p1
    ghc-options: -O2
    dependencies:
      - base
  p3:
    main: Main.hs
    source-dirs: problems/p3
    ghc-options: -O2
    dependencies:
      - base
  p4:
    main: Main.hs
    source-dirs: problems/p4
    ghc-options: -O2
    dependencies:
      - base
  p5:
    main: Main.hs
    source-dirs: problems/p5
    ghc-options: -O2
    dependencies:
      - base
  p6:
    main: Main.hs
    source-dirs: problems/p6
    ghc-options: -O2
    dependencies:
      - base
  p8:
    main: Main.hs
    source-dirs: problems/p8
    ghc-options: -O2
    dependencies:
      - base
  p22:
    main: Main.hs
    source-dirs: problems/p22
    ghc-options: -O2
    dependencies:
      - base
  p28:
    main: Main.hs
    source-dirs: problems/p28
    ghc-options: -O2
    dependencies:
      - base
  p29:
    main: Main.hs
    source-dirs: problems/p29
    ghc-options: -O2
    dependencies:
      - base
  p38:
    main: Main.hs
    source-dirs: problems/p38
    ghc-options: -O2
    dependencies:
      - base
  p509:
    main: Main.hs
    source-dirs: problems/p509
    ghc-options: -O2
    dependencies:
      - base
  p70:
    main: Main.hs
    source-dirs: problems/p70
    ghc-options: -O2
    dependencies:
      - base
  p1137:
    main: Main.hs
    source-dirs: problems/p1137
    ghc-options: -O2
    dependencies:
      - base
  p95:
    main: Main.hs
    source-dirs: problems/p95
    ghc-options: -O2
    dependencies:
      - base
  p96:
    main: Main.hs
    source-dirs: problems/p96
    ghc-options: -O2
    dependencies:
      - base
  p52:
    main: Main.hs
    source-dirs: problems/p52
    ghc-options: -O2
    dependencies:
      - base
  p51:
    main: Main.hs
    source-dirs: problems/p51
    ghc-options: -O2
    dependencies:
      - base
  p89:
    main: Main.hs
    source-dirs: problems/p89
    ghc-options: -O2
    dependencies:
      - base
  p3211:
    main: Main.hs
    source-dirs: problems/p3211
    ghc-options: -O2
    dependencies:
      - base
  p118:
    main: Main.hs
    source-dirs: problems/p118
    ghc-options: -O2
    dependencies:
      - base
  p401:
    main: Main.hs
    source-dirs: problems/p401
    ghc-options: -O2
    dependencies:
      - base
  p967:
    main: Main.hs
    source-dirs: problems/p967
    ghc-options: -O2
    dependencies:
      - base
  p77:
    main: Main.hs
    source-dirs: problems/p77
    ghc-options: -O2
    dependencies:
      - base
  p1344:
    main: Main.hs
    source-dirs: problems/p1344
    ghc-options: -O2
    dependencies:
      - base
  p3272:
    main: Main.hs
    source-dirs: problems/p3272
    ghc-options: -O2
    dependencies:
      - base
  p1641:
    main: Main.hs
    source-dirs: problems/p1641
    ghc-options: -O2
    dependencies:
      - base
  p1175:
    main: Main.hs
    source-dirs: problems/p1175
    ghc-options: -O2
    dependencies:
      - base
  p3099:
    main: Main.hs
    source-dirs: problems/p3099
    ghc-options: -O2
    dependencies:
      - base
  p1447:
    main: Main.hs
    source-dirs: problems/p1447
    ghc-options: -O2
    dependencies:
      - base
  p1646:
    main: Main.hs
    source-dirs: problems/p1646
    ghc-options: -O2
    dependencies:
      - base
  p1688:
    main: Main.hs
    source-dirs: problems/p1688
    ghc-options: -O2
    dependencies:
      - base
  p894:
    main: Main.hs
    source-dirs: problems/p894
    ghc-options: -O2
    dependencies:
      - base
  p119:
    main: Main.hs
    source-dirs: problems/p119
    ghc-options: -O2
    dependencies:
      - base
  p1925:
    main: Main.hs
    source-dirs: problems/p1925
    ghc-options: -O2
    dependencies:
      - base
  p3304:
    main: Main.hs
    source-dirs: problems/p3304
    ghc-options: -O2
    dependencies:
      - base
  p3178:
    main: Main.hs
    source-dirs: problems/p3178
    ghc-options: -O2
    dependencies:
      - base
  p1415:
    main: Main.hs
    source-dirs: problems/p1415
    ghc-options: -O2
    dependencies:
      - base
  p17:
    main: Main.hs
    source-dirs: problems/p17
    ghc-options: -O2
    dependencies:
      - base
  p216:
    main: Main.hs
    source-dirs: problems/p216
    ghc-options: -O2
    dependencies:
      - base
  p2081:
    main: Main.hs
    source-dirs: problems/p2081
    ghc-options: -O2
    dependencies:
      - base
  p3537:
    main: Main.hs
    source-dirs: problems/p3537
    ghc-options: -O2
    dependencies:
      - base
